/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.clayton.telas.Inicial;

import com.clayton.metodos.CapturaDigital;
import com.clayton.metodos.DigitalPersistencia;
import com.clayton.model.CadDigital;
import com.clayton.model.CadPessoa;
import com.clayton.telas.Inicial.cadastropessoa.TelaCadPessoa;
import com.clayton.telas.cadastrardigital.CadastrodeDigital;
import com.digitalpersona.onetouch.DPFPFingerIndex;
import javax.swing.JCheckBox;
import com.clayton.telas.salvararquivo.SalvarDigital;
import com.clayton.telas.validar.Painel;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author clayton
 */
public class NovaTelaBackup extends javax.swing.JFrame {

    /**
     * Creates new form NovaTela
     */
    public NovaTelaBackup() {
        initComponents();
        //setSize (350, 300);
        setLocation((tela.width - this.getSize().width) / 2, (tela.height - this.getSize().height) / 2);

    }
    Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();

    private CapturaDigital me;

    private SpinnerNumberModel maxCount = new SpinnerNumberModel(DPFPFingerIndex.values().length, 0, DPFPFingerIndex.values().length, 1);
    private JSpinner maxCountSpinner;
    private final JButton enrollButton = new JButton("Registrar Impressão Digital");
    final JCheckBox enforceFailure = new JCheckBox("Forçar cadastro quando ocorrer falhas na leitura");

    public CapturaDigital getMe() {
        return me;
    }

    public void setMe(CapturaDigital me) {
        this.me = me;
    }

    public SpinnerNumberModel getMaxCount() {
        return maxCount;
    }

    public void setMaxCount(SpinnerNumberModel maxCount) {
        this.maxCount = maxCount;
    }

    public JSpinner getMaxCountSpinner() {
        return maxCountSpinner;
    }

    public void setMaxCountSpinner(JSpinner maxCountSpinner) {
        this.maxCountSpinner = maxCountSpinner;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editar = new javax.swing.JButton();
        painel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buscaid = new javax.swing.JTextField();
        BuscarPessoa = new javax.swing.JButton();
        buscaid1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        salvar1 = new javax.swing.JButton();
        editar1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editar.setText("Teste Alterar Pessoa");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        jLabel1.setText("Digite o ID da Digital-Pessoa");

        buscaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaidActionPerformed(evt);
            }
        });

        BuscarPessoa.setText("Buscar Digital da Pessoa");
        BuscarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPessoaActionPerformed(evt);
            }
        });

        buscaid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaid1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Digite o ID da Pessoa");

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addComponent(BuscarPessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(buscaid1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addComponent(buscaid, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))))
            .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(428, Short.MAX_VALUE)))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                        .addComponent(buscaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BuscarPessoa)
                    .addComponent(buscaid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                    .addContainerGap(196, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(90, 90, 90)))
        );

        salvar1.setText("Salvar Digitais Pessoa");
        salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar1ActionPerformed(evt);
            }
        });

        editar1.setText("Alterar Pessoa Digitais");
        editar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Sistema");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, 0));
        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Impressão Digital");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, 0));
        jMenuItem6.setText("Cadastrar Pessoa");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        jMenuItem5.setText("Alterar Digitais Cadastradas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
        jMenuItem2.setText("Salvar Em Arquivo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, 0));
        jMenuItem4.setText("Validar Digital");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editar1)
                    .addComponent(salvar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editar)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Painel pa = new Painel();
        pa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        SalvarDigital sa = new SalvarDigital();
        sa.setMe(getMe());
        sa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:

        if (me != null) {
            CadastrodeDigital sa = new CadastrodeDigital();
            sa.setTemplates(me.getTemplates());
            sa.UpdateUIP();
            boolean cadastro = true;
            sa.setCadastro(cadastro);
            sa.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Este Usuario, não possui Digitais  Cadastradas.\n"
                    + "Por favor, clique em Cadastrar Digitais ou pressione C do teclado");
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        DigitalPersistencia di = new DigitalPersistencia();

        CadPessoa lo = new CadPessoa();
        Integer id;
        id = Integer.parseInt(buscaid.getText());
        lo.setIduser(id);
        lo.setLogin("Clayton Alterado");
        String b = di.AlteraLoginTeste();
        JOptionPane.showMessageDialog(rootPane, b);
    }//GEN-LAST:event_editarActionPerformed

    private void buscaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaidActionPerformed

    private void BuscarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPessoaActionPerformed
        DigitalPersistencia di = null;
        di = new DigitalPersistencia();
        byte[] b;

        CadDigital caddig = new CadDigital();
        CadPessoa pe = new CadPessoa();
        Integer id;
        id = Integer.parseInt(buscaid.getText());
        caddig = di.BuscaDigitalALL(id);
        CapturaDigital mer = new CapturaDigital();
        mer.setTemplates(mer.Injetar_Digitais_Pessoa(caddig));
        // se retornar com digitais ja inseri para alterar
        CadastrodeDigital sa = new CadastrodeDigital();
        pe = di.BuscaPessoa(id);
        sa.setTemplates(mer.getTemplates());
        sa.UpdateUIP();
        sa.setPe(pe);
        sa.setAlterar(true);
        sa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BuscarPessoaActionPerformed

    private void salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar1ActionPerformed
        if (getMe() == null) {
            JOptionPane.showMessageDialog(rootPane, "Voce ainda não Cadastrou Ditais");

        } else {

            DigitalPersistencia di = new DigitalPersistencia();
            di.setCapturadigital(getMe());
            Integer idd;
            idd = Integer.parseInt(buscaid1.getText());
            CadPessoa pe = new CadPessoa(idd, "Clayton Ferraz");
            CadDigital cad = new CadDigital(pe);
            di.setCaddigital(cad);
            di.setLogin(pe);
            di.ExtrairDigitais();
            String b = di.CadastraDigitalTeste();
            JOptionPane.showMessageDialog(rootPane, b);

        }
    }//GEN-LAST:event_salvar1ActionPerformed

    private void editar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar1ActionPerformed
        if (getMe() == null) {
            JOptionPane.showMessageDialog(rootPane, "Voce ainda não Cadastrou Ditais");

        } else {

            DigitalPersistencia di = new DigitalPersistencia();
            di.setCapturadigital(getMe());
            Integer id;
            id = Integer.parseInt(buscaid.getText());
            CadPessoa pe = new CadPessoa(id, "Clayton Ferraz");
            CadDigital cad = new CadDigital(pe);
            Integer idd;
            idd = Integer.parseInt(buscaid1.getText());
            cad.setId(idd);
            di.setCaddigital(cad);
            di.setLogin(pe);
            di.ExtrairDigitais();
            String b = di.AlteraDigitalTeste();
            JOptionPane.showMessageDialog(rootPane, b);

        }
    }//GEN-LAST:event_editar1ActionPerformed

    private void buscaid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaid1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        TelaCadPessoa te = new TelaCadPessoa();
        te.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaTelaBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaTelaBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaTelaBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaTelaBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NovaTelaBackup().setVisible(true);

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarPessoa;
    private javax.swing.JTextField buscaid;
    private javax.swing.JTextField buscaid1;
    private javax.swing.JButton editar;
    private javax.swing.JButton editar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel painel;
    private javax.swing.JButton salvar1;
    // End of variables declaration//GEN-END:variables
}
